Update Docs
tiramisulabs/seyfert-docs pull request #10
Opened 2024-03-15 22:49 UTC by PabloRNC

# CHANGES

Created `Miscellaneous section` for utilities or non-prior or required guides. 

Created send messages guide to make the learner of seyfert to be familiarized with sending diffrent types or messages

Moved `Music Library` section into miscellaneous guide.

# Annotations

Please check if I have explained well and if the examples are well made. Thanks 🙏.

2024-03-15 23:12 UTC, FreeAoi commented on src/content/docs/misc/sending-messages.md
> +
here remove the spaces between the decorator and the class

2024-03-15 23:12 UTC, FreeAoi commented on src/content/docs/misc/sending-messages.md
> +        ctx.client.messages.write("channelId", { content: "Hello World 👋" })
here instead of use "channelId" as placeholder you could get the actual channel the interaction is begin created

2024-03-15 23:12 UTC, FreeAoi commented on src/content/docs/misc/sending-messages.md
> +        ctx.write({ embeds: [embed] })
padding problem

2024-03-15 23:12 UTC, FreeAoi commented on src/content/docs/misc/sending-messages.md
> +        ctx.write({ content: "Hello World 👋", components: [buttonRow, menuRow] })
check padding here

2024-03-16 02:04 UTC, socram03 requested changes

2024-03-16 02:04 UTC, socram03 commented on src/content/docs/misc/sending-messages.md
> +```
```suggestion
```ts title="src/commands/helloworld.ts" ins={10-12} showLineNumbers
import {
	Command,
	Declare
} from "seyfert";

@Declare({
	name: "helloworld",
	description: "Send a basic hello world message."
})
export default class HelloWorldCommand extends Command {
	async run(ctx: CommandContext) {
        ctx.write({ content: "Hello World 👋" })
    }
}
```
```

2024-03-16 02:07 UTC, socram03 commented on src/content/docs/misc/sending-messages.md
> +    }
```suggestion
	async run(ctx: CommandContext) {
        ctx.client.messages.write(ctx.channelId, { content: "Hello World 👋" })
    }
```
It is more than understandable where the channel id comes from.

2024-03-16 13:34 UTC, FreeAoi reviewed
it seems right

2024-03-16 18:09 UTC, socram03 approved these changes

2024-03-16 18:09 UTC, socram03 approved these changes

2024-03-16 18:10 UTC, merged

2024-03-16 19:43 UTC, PabloRNC commented
Yeah ❤️