Update/Fix some things
tiramisulabs/seyfert-docs pull request #13
Opened 2024-03-25 22:12 UTC by NoBody-UU

🐒

2024-03-25 22:43 UTC, PabloRNC submitted a review, later dismissed
For a better sintaxt you can write: Moreover, categories can be created within a folder and then put the command into it.

2024-03-25 22:56 UTC, socram03 requested changes

2024-03-25 22:56 UTC, socram03 commented on src/content/docs/commands/subcommands.mdx
> +export default class AccountCommand extends Command {}
```suggestion
})
// Being in the same folder with @AutoLoad() you can save this
@Options([AddCommand, DeleteCommand])
export default class AccountCommand extends Command {}
```

2024-03-25 22:56 UTC, socram03 commented on src/content/docs/guides/first-command.mdx
> +import { MessageFlags } from 'seyfert/lib/common';
Adding this breaks highlight formatting, moves markdown values

2024-03-25 22:56 UTC, socram03 commented on src/content/docs/guides/first-command.mdx
> +		- **ping.ts** // Also, you can create a folder for categories and put the command there.
Move the comment up, at the end of the line it is barely visible

2024-03-26 00:26 UTC, socram03 approved these changes, later dismissed

2024-03-26 00:35 UTC, FreeAoi reviewed
HI! could you revert this on try to fetch contributors by fetch api pls?

2024-03-26 00:47 UTC, FreeAoi commented on src/content/docs/commands/subcommands.mdx
> +export class CreateCommand extends SubCommand {
When using autoload you must export default the SubCommand class!!

2024-03-26 15:37 UTC, FreeAoi approved these changes

2024-03-26 15:39 UTC, MARCROCK22 approved these changes

2024-03-26 15:40 UTC, merged