create components guide
tiramisulabs/seyfert-docs pull request #14
Opened 2024-03-27 18:03 UTC by PabloRNC

In this pull request I am going to create a guide for making and handling components within seyfert as requested by Socram.

# CHANGES

Updated sidebar for creating `Components` category within guide.

Created two sections: `introduction` and `building components`.

2024-03-27 19:47 UTC, PabloRNC commented
[eb6a920](https://github.com/tiramisulabs/seyfert-docs/pull/14/commits/eb6a92058275e5e43d5b64a6ede6f4085a21d620) I have partially added all the types of select menus as it was an [issue](https://github.com/tiramisulabs/seyfert/issues/161) regarding MentionableSelectMenu.

2024-03-27 21:18 UTC, socram03 requested changes

2024-03-27 21:18 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +const stringRow = new ActionRow().setComponents(stringMenu);
```suggestion
const stringRow = new ActionRow<StringSelectMenu>().setComponents(stringMenu);
```

2024-03-27 21:18 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +.setComponents(button)
```suggestion
const row = new ActionRow<Button>().setComponents(button)
```
It is very common to get a type error here if you do not specify the component that will be in the action row.

2024-03-27 21:18 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +const userRow = new ActionRow().setComponents(userMenu);
```suggestion
const userRow = new ActionRow<UserSelectMenu>().setComponents(userMenu);
```

2024-03-27 21:18 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +const roleRow = new ActionRow().setComponents(roleMenu);
```suggestion
const roleRow = new ActionRow<RoleSelectMenu>().setComponents(roleMenu);
```

2024-03-27 21:18 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +const channelRow = new ActionRow().setComponents(channelMenu);
```suggestion
const channelRow = new ActionRow<ChannelSelectMenu>().setComponents(channelMenu);
```

2024-03-27 21:18 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +const mentionableRow = new ActionRow().setComponents(mentionableMenu);
```suggestion
const mentionableRow = new ActionRow<MentionableSelectMenu>().setComponents(mentionableMenu);
```

2024-03-27 21:18 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +import { TextInputStyle } from 'discord-api-types';
```suggestion
import { TextInputStyle } from 'discord-api-types/v10';
```

2024-03-28 02:48 UTC, socram03 requested changes

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +import { ButtonStyle } from 'discord-api-types';
```suggestion
import { ButtonStyle } from 'discord-api-types/v10';
```

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +)
```suggestion
const stringMenu = new StringSelectMenu({ label: 'Option 1', value: '1' })
.setCustomId('string-menu')
.setPlaceholder('Select an string option')
.setOptions(
    new StringSelectOption().setLabel('Option 2').setValue('2')
)
```
This builder now only accepts one other builder

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/components/building-components.mdx
> +.setDefaultMentionables('123456789', '987654321')
```suggestion
.setDefaultMentionables({ type: 'User', id: '123456789' }, { type: 'Role', id: '987654321'})
```
In this specific menu, if we are forced to ask for the type

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/components/handling-components.md
> +    componentType = ComponentType.Button
```suggestion
    componentType = "Button" as const;
```

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/components/handling-components.md
> +    }
```suggestion
    // this can be promise too
    filter(context: ComponetContext<typeof this.componentType>) {
        return context.customId === 'hello-world';
    }
```

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/components/handling-components.md
> +    type ButtonInteraction
```suggestion
    type ComponentContext
```

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/components/handling-components.md
> +}
The same issues, now seyfert has component context

2024-03-28 02:48 UTC, socram03 commented on src/content/docs/misc/sending-messages.md
Add a note remembering the components section here

2024-03-28 09:49 UTC, PabloRNC commented on src/content/docs/components/building-components.mdx
> +)
So instead, making two options with the builder.  As you have made only one. I will make as pair as the old example.

2024-03-28 13:08 UTC, PabloRNC commented
I have only need to resolve your last review about adding a components section. I don't know what you mean.

2024-03-28 17:01 UTC, socram03 requested changes

2024-03-28 17:01 UTC, socram03 commented on src/content/docs/components/collectors.md
> +Seyfert includes `message collectors` which are an easy way to handle does interactions received from an specific message and make you able to get more context about what had happened before sending
```suggestion
Seyfert includes `components message collectors` which are an easy way to handle does components interactions received from an specific message and make you able to get more context about what had happened before sending the component.
```

2024-03-28 17:01 UTC, socram03 commented on src/content/docs/components/collectors.md
> +                timeout: 1e3 //1000ms
```suggestion
            {
                filter: (i) => i.user.id === ctx.author.id,
                onStop(reason, refresh){
                    //this will refresh the collector everytime it stops by timeout
                    if(reason === 'idle') return refresh();
                },
                idle: 1e3 //1000ms
```
The idea of timeout is to terminate the collector, for this it is correct to use idle

2024-03-28 17:01 UTC, socram03 commented on src/content/docs/components/collectors.md
> +            if(i.isButton()) return await i.write({ content: 'Hello World 👋' })
`i.isButton()` may be part of the filter, we should consider adding it to the options.

2024-03-28 18:23 UTC, socram03 approved these changes, later dismissed

2024-03-28 18:31 UTC, socram03 approved these changes

2024-03-28 18:45 UTC, MARCROCK22 approved these changes

2024-03-28 18:46 UTC, merged