feat: add prefix commands guide
tiramisulabs/seyfert-docs pull request #18
Opened 2024-04-04 17:17 UTC by PabloRNC

# CHANGES

Added `prefix commands` guide within Miscellaneous section.

This section covers:

* Set up of client options and handling of prefixes commands
* Replying to prefix commands instead of sending a raw message.
* Prefix commands options 
* Defer replying the prefix command and covering deferReplyResponse option.

Some notes I have added into the guide:

* There is no way to select which command will be prefix or application command if we use both in our application as both will be created (soon pls). 
* Subcommands can be created within seyfert for prefix commands.

### HAVE A GOOD READ

2024-04-04 23:20 UTC, socram03 requested changes

2024-04-04 23:20 UTC, socram03 commented on src/content/docs/commands/prefix-commands.mdx
> +            //here you can handle whatever prefixes you will want to be consider depending on the message data.
Add warp option to codeblock or split comment, is too large

2024-04-04 23:20 UTC, socram03 commented on src/content/docs/commands/prefix-commands.mdx
> +            //here you can handle whichever prefixes you will want to be consider depending on the message data.
the same as above

2024-04-04 23:20 UTC, socram03 commented on src/content/docs/commands/prefix-commands.mdx
> +Here is a simple example of how we make the previous command but instead of cross posting the current command cross posing another message, fetching it by its id.
Add example how to use this as discord user

2024-04-04 23:20 UTC, socram03 commented on src/content/docs/commands/prefix-commands.mdx
> +        const message = await ctx.client.messages.fetch(id, ctx.channelId);
```suggestion
        const message = await ctx.client.messages.fetch(ctx.options.id, ctx.channelId);
```

2024-04-04 23:20 UTC, socram03 commented on src/content/docs/commands/prefix-commands.mdx
> +            //here you can handle whichever prefixes you will want to be consider depending on the message data.
Another

2024-04-04 23:20 UTC, socram03 commented on src/content/docs/commands/prefix-commands.mdx
> +        await ctx.client.messages.crosspost(id, ctx.channelId);
```suggestion
        await ctx.client.messages.crosspost(ctx.options.id, ctx.channelId);
```

2024-04-05 15:04 UTC, socram03 approved these changes

2024-04-06 01:17 UTC, MARCROCK22 approved these changes

2024-04-06 01:17 UTC, merged