Support for i18n
tiramisulabs/seyfert-docs pull request #19
Opened 2024-04-04 19:38 UTC by FabrizioCoder

## Multilang

2024-04-04 20:04 UTC, FreeAoi commented
Hi, please check errors and thx

2024-04-04 20:04 UTC, FreeAoi reviewed
Check error

2024-04-04 22:16 UTC, FabrizioCoder commented
# Getting Started was translated into Spanish

2024-04-14 19:11 UTC, socram03 requested changes
Los titulos de los archivos se quedaron en ingles

2024-04-14 19:11 UTC, socram03 commented on src/content/docs/es/index.mdx
> +Seyfert es una poderosa librería que se enfoca en Discord y su API en bots. Ofrece soporte para aplicaciones escalables y proporciona utilidades únicas.
```suggestion
Seyfert es una poderosa librería que se enfoca en Discord y su API para bots. Ofrece soporte para aplicaciones escalables y proporciona utilidades únicas.
```

2024-04-14 19:18 UTC, FabrizioCoder commented on src/content/docs/es/index.mdx
> +Seyfert es una poderosa librería que se enfoca en Discord y su API en bots. Ofrece soporte para aplicaciones escalables y proporciona utilidades únicas.
ok

2024-04-14 19:18 UTC, socram03 approved these changes

2024-04-14 21:29 UTC, closed without merging